version: '3'
services:
  web:
    image: apache
    build: ./
    volumes:
      -  ./public-html/:/var/www/html/
    container_name: apache_web
    ports:
      - "80:80"
  db:
    image: mysql:8.0
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root      
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #- database/:/var/lib/mysql/
      - database/:/docker-entrypoint.sh
    networks:
      - default
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "5000:80"
volumes:
  database:
